# Generated by Django 4.2.4 on 2023-08-09 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price List',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.PositiveIntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.pricelist')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 18, 19, 15, 677728))),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.pricelist')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.partner')),
            ],
        ),
    ]
