# Generated by Django 4.2.4 on 2023-08-09 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_remove_sale_price_alter_partnerstorage_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mystorage',
            options={'verbose_name': 'My Storage', 'verbose_name_plural': 'My Storage'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='partnerstorage',
            options={'verbose_name': 'Partner Storage', 'verbose_name_plural': "Partners' Storages"},
        ),
        migrations.RemoveField(
            model_name='partnerstorage',
            name='total_sales',
        ),
        migrations.AlterField(
            model_name='partnerstorage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.mystorage'),
        ),
        migrations.AlterField(
            model_name='partnerstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 18, 52, 22813)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 18, 52, 22813)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.mystorage'),
        ),
    ]
