# Generated by Django 4.2.4 on 2023-08-09 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_alter_mystorage_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 19, 48, 939400)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 19, 48, 939400)),
        ),
    ]
