# Generated by Django 4.2.4 on 2023-08-09 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_alter_partnerstorage_updated_at_alter_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerstorage',
            options={'ordering': ('-pk',), 'verbose_name': 'Partner Storage', 'verbose_name_plural': "Partners' Storages"},
        ),
        migrations.AlterField(
            model_name='partnerstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 42, 22, 790162)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 42, 22, 790162)),
        ),
    ]
