# Generated by Django 4.2.4 on 2023-08-09 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0008_alter_partnerstorage_updated_at_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 41, 35, 722611)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 41, 35, 722611)),
        ),
    ]
