# Generated by Django 4.2.4 on 2023-08-09 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0009_alter_partnerstorage_updated_at_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 44, 32, 576849)),
        ),
        migrations.AlterField(
            model_name='partnerstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 44, 32, 576849)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 44, 32, 576849)),
        ),
    ]
