# Generated by Django 4.2.4 on 2023-08-09 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0011_alter_partner_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 48, 32, 83183)),
        ),
        migrations.AlterField(
            model_name='partner',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 48, 32, 83843)),
        ),
        migrations.AlterField(
            model_name='partnerstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 48, 32, 84384)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 48, 32, 84384)),
        ),
    ]
