# Generated by Django 4.2.4 on 2023-08-09 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_alter_partner_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 2, 0, 13, 734846)),
        ),
        migrations.AlterField(
            model_name='partnerstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 2, 0, 13, 734846)),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 2, 0, 13, 734846)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 2, 0, 13, 734846)),
        ),
    ]
