# Generated by Django 4.2.4 on 2023-08-15 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0016_alter_partner_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 17, 57, 53, 163646)),
        ),
        migrations.AlterField(
            model_name='partnerstorage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 17, 57, 53, 163646)),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 17, 57, 53, 163646)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 17, 57, 53, 163646)),
        ),
    ]
